### ISSUE TITLE
羡慕啊

### ISSUE THREAD

**Issue by xiashuijun** [Wangzhike/MIT6.824_DistributedSystem#2]
兄弟，能录个视频最好了，谢谢

**Comment by Wangzhike** [comment]
也刚刚入门，视频啥的搞不起来，加上毕设时间也不够。这几天把看论文的笔记分享出来吧，算是一个翻译的参考。嘻嘻，一起交流学习。

**Comment by xiashuijun** [comment]
> 也刚刚入门，视频啥的搞不起来，加上毕设时间也不够。这几天把看论文的笔记分享出来吧，算是一个翻译的参考。嘻嘻，一起交流学习。

好的，谢谢
